
export const ActionTypes = {

    FETCH_LEAVES: "FETCH_LEAVES",
    FETCH_LEAVE: "FETCH_LEAVE",
    SET_LEAVES: "SET_LEAVES",
    FETCH_LEAVE_TYPES: "FETCH_LEAVE_TYPES",
    FETCH_EMP_TYPES: "FETCH_EMP_TYPES",
    SELECTED_LEAVE: "SELECTED_LEAVE",
    REMOVE_SELECTED_LEAVE: "REMOVE_SELECTED_LEAVE",
    FETCH_SELECTED_LEAVE_HISTORY: "FETCH_SELECTED_LEAVE_HISTORY",
    SET_SELECTED_LEAVE_LOG: "SET_SELECTED_LEAVE_LOG",
    UPDATE_LEAVE: "UPDATE_LEAVE",
    SUBMIT_LEAVE: "SUBMIT_LEAVE",
    APPROVE_LEAVE: "APPROVE_LEAVE",
    REJECT_LEAVE: "REJECT_LEAVE",
    FETCH_AUTHOR_DETAILS:"FETCH_AUTHOR_DETAILS",
    FETCH_TOTAL_LEAVE_COUNT:"FETCH_TOTAL_LEAVE_COUNT"
};