export const SettingsActionTypes = {
    GET_DMSSETTINGS: "GET_DMSSETTINGS",
    GET_DMSSETTINGS_BY_ID: "GET_DMSSETTINGS_BY_ID",
    GET_DMSSETTINGS_BY_APP_ID: "GET_DMSSETTINGS_BY_APP_ID",
    UPDATE_DMSSETTINGS: "UPDATE_DMSSETTINGS",
    DELETE_DMSSETTINGS: "DELETE_DMSSETTINGS"

}