export const ActionTypes = {
  GET_DIVISION_DROPDOWN: "GET_DIVISION_DROPDOWN",
  GET_SUITE_DROPDOWN: "GET_SUITE_DROPDOWN",
  CREATE_DMS_APPLICATION: "CREATE_DMS_APPLICATION",
  FETCH_DMS_APPLICATIONS: "FETCH_DMS_APPLICATIONS",
  FETCH_DMS_APPLICATION_BY_ID: "FETCH_DMS_APPLICATION_BY_ID",
  EDIT_DMS_APPLICATION: "EDIT_DMS_APPLICATION",
  DELETE_DMS_APPLICATION: "DELETE_DMS_APPLICATION",
};
